---
  reference_by_usb: true
  play_from_video: false
  video_files:
    - 'output_right.avi'    
    - 'output_left.avi'
  cameras:
    - '0-8'
    - '0-2'
  calib_files:
    - 'params/cam1.yaml'    
    - 'params/cam2.yaml'
  apply_KD: false
  display: true
  print_markers: true
  remote_ip: "127.0.0.1"
  remote_port: 5000
  fps: 50
  gain: 10
  exposure: 30
