---
  local_ip: "127.0.0.1"
  local_port: 10000
  cam1_port: 5000
  cam1_id:   0
  cam2_port: 5000
  cam2_id:   1
  
  cam1_params_path: '/home/rouholla/myData/Robotics/projects/RaspiTrack/server_nodes/reconstruction/Batch/recorded_data/planar/5002_0.yaml'
  cam2_params_path: '/home/rouholla/myData/Robotics/projects/RaspiTrack/server_nodes/reconstruction/Batch/recorded_data/planar/5002_1.yaml'
  max_markers_per_image: 1
  ext_params_path: '/home/rouholla/myData/Robotics/projects/RaspiTrack/server_nodes/reconstruction/Batch/ext_params.pckl'
  record: false
  path: '/home/ust0/IR_Tracker_WS/RaspiTrack/server_nodes/udp_bridge/standalone/dataset_tmp_dir'
  print_markers: ture
