---
  reference_by_usb: false
  play_from_video: true
  cameras:
    - 'output_left.avi'
    - 'output_right.avi'
  calib_files:
    - 'params/right_params.yml'
    - 'params/right_params.yml'
  display: true
  print_markers: true
  remote_ip: "127.0.0.1"
  remote_port: 5000
  fps: 30
  gain: 10
  exposure: 5
