---
  reference_by_usb: true
  play_from_video: false
  cameras:
    - '0-1.1' #Camera #1
    - '0-1.2' #Camera #2
  calib_files:
    - 'params/right_params.yml'
    - 'params/right_params.yml'
  display: true
  print_markers: false
  remote_ip: "192.168.1.1"
  remote_port: 5000
  fps: 50
  gain: 10
  exposure: 5
