---
  reference_by_usb: true
  play_from_video: true
  cameras:
    - '0-3' #Camera #3
    - '0-4' #Camera #4
  calib_files:
    - 'params/cam3_params.yml'
    - 'params/cam4_params.yml'
  display: true
  print_markers: false
  remote_ip: "192.168.1.1"
  remote_port: 5001
  fps: 50
  gain: 10
  exposure: 5
