---
  reference_by_usb: true
  play_from_video: true
  cameras:
    - '0-6' #left camera
    - '0-5' #right camera
  calib_files:
    - 'params/left_params.yaml'
    - 'params/right_params.yaml'
  display: true
  print_markers: false
  remote_ip: "192.168.1.4"
  remote_port: 5002
  fps: 50
  gain: 50
  exposure: 10
