---
  reference_by_usb: true
  play_from_video: true
  cameras:
    - '0-3' #cam 3
    - '0-4' #cam 4
  apply_KD: false
  calib_files:
    - 'params/cam1_params.yaml'
    - 'params/cam2_params.yaml'
  display: true
  print_markers: true
  remote_ip: "192.168.1.4"
  remote_port: 5001
  fps: 50
  gain: 30
  exposure: 10
