---
  local_ip:  "127.0.0.1"
  remote_ip: "127.0.0.1"
  remote_port: 10000

  camera_ports:
    - 5000
  record: false
  path: '/home/ust0/IR_Tracker_WS/RaspiTrack/server_nodes/udp_bridge/standalone/dataset_tmp_dir'
  print_markers: false
